### ISSUE TITLE
Componente de Login

### ISSUE THREAD

**Issue by wagnerfillio** [williamoliveira/project-planner#4]
Gosto de bootstrap e também gostei do seu projeto.

Então queria saber se você pode me ajudar.

Utilizando o mesmo padrão que já está no projeto, como posso criar uma rota de login, sem exibir o componente navbar ?

Não precisa das funções de logar, queria somente o componente login.

**Comment by williamoliveira** [comment]
Cara, vou te falar que não lembro nem o que esse projeto faz

**Comment by wagnerfillio** [comment]
É só um layout inicial basico com reactstrap.

Tem um navbar, com 2 opções, um componente modal e só!

Daí eu queria colocar uma pagina de login e queria que voce me ajudasse.
